name: my-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - numpy=2.2.5
  - pandas=2.3.3
  - pip=26.0.1
  - scipy=1.15.3
  - setuptools=80.10.2
  - pip:
      - exceptiongroup==1.3.1
      - iniconfig==2.3.0
      - pluggy==1.6.0
      - pygments==2.19.2
      - pytest==9.0.2
      - rapidfuzz==3.14.3
      - tomli==2.4.0
      - typing-extensions==4.15.0
