---
title: "Technology Review"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

**Python Package Choices**

1.  Package for leetspeak decoding

-   **Name:** floft/leetspeak (<https://github.com/floft/leetspeak>)
-   **Author:** floft
-   **Purpose:** a leetspeak to english translator that uses the
    probability of word usage taken from the Project Gutenberg from all
    the possibilities it can generate Package for leetspeak decoding

2.  Another package for leetspeak decoding

-   **Name:**floft/leetspeak(<https://github.com/Monotoba/leetspeak-encoder-decoder>)
-   **Author:**Monotoba
-   **Purpose:** a leetspeak to multiple languages translator that
    allows for encoding and decoding leetspeak. The package also has a
    dictionary for multiple character replacements in different
    languages and can identify the correct character and language based
    on language identifiers

3.  Package for fuzzy matching (calculates difference or similarity
    between two strings)

-   **Name:** RapidFuzz
    (<https://pypi.org/project/RapidFuzz/#description>)
-   **Author:** Max Bachmann
-   **Purpose:** Calculates similarity or “distance” between two or more
    strings and assigns a score/ratio based on this distance. Builds off
    of string similarities calculations from FuzzyWuzzy library

4.  Package for fuzzy matching (calculates difference or similarity
    between two strings)

-   **Name:** TheFuzz (<https://pypi.org/project/thefuzz/>)
-   **Author:** Adam Cohen
-   **Purpose:** Uses Levenshtein distance to calculate similarity or
    “distance” between strings and assigns a score/ratio based on this
    distance. Package for pyleetspeak (prob not since for encoding not
    decoding)

5.  Leetspeak encoder(this may not be useful for our project)

-   **Name:** pyleetspeak (<https://github.com/Huertas97/pyleetspeak>)
-   **Author:** Álvaro Huertas García
-   **Purpose:**

**Package Comparison**

**Leetspeak-encoder-decoder** -

-   This function theoretically simplifies the word needed to be done
    since it acts as a leetspeak decoder that can take in leetspeak
    phrases and decode them to “regular” english.

-   Pros:

    -   Very easy to call: decode_leet(text, lang)

    -   Gives you a replacement dictionary that is used

-   Cons:

    -   Not pip installable so integration is messy (have to clone repo)

    -   It produces outputs that can be lossy or normalized, which is
        risky since ever character matters in plates

    -   Has a low adoption signal which can be seen by the low forks and
        ratings. This could mean higher maintenance risks.

**RapidFuzz**

-   This function can be used to find similarity between words to find
    matches/closest match. This is paired with additional functions we
    write to do one character variant replacement, normalization, and
    any substring matches.

-   Pros:

    -   Very fast and actively maintained

    -   Has useful APIs: fuzz.ratio, fuzz.partial_ratio, process.extract

    -   It is great for finding the closest “bad-word candidate” after
        normalizing

-   Cons:

    -   Requires own preprocessing

    -   Might require some threshold tuning to figure out what score
        means its a good enough match

-   Using this package requires that we need to do additional
    work/preprocessing

-   Issues on github: 31; Forks: 151

-   Installed using pip

-   Plenty of examples used

**The Fuzz**

-   This function can be used to find similarity between words to find
    matches/closest match. This is paired with additional functions we
    write to do one character variant replacement, normalization, and
    any substring matches.

-   Pros:

    -   Has a simple API with lots of tutorials on how to use

    -   Has been used in lots of older codes

-   Cons:

    -   Typically slower than rapidfuzz

    -   Has the same use case as rapidfuz

-   Using this package requires that we need to do additional
    work/preprocessing

-   Issues on github: 39; Forks: 154

-   Installed using pip

-   Plenty of examples used

**Demo**

Insert code demo here

**Our package choice**

Our package choice is RapidFuzz. This is due to the its versatility and
maintenance. In our project we expect users to be able to enter a
license plate and quickly and easily be able to output a liklihood of
getting approved. The use of RapidFuzz with access to several APIs will
facilitate the a fast and simple user experience which we would like to
prioritize.
